import 'package:flutter/material.dart';

class WorldsCatalog {
  static final List<Map<String, dynamic>> worlds = [
    {
      'id': 'w1',
      'name': 'Reino Numérico',
      'subtitle': 'El Origen de los Números',
      'icon': Icons.calculate,
      'color': Colors.blueAccent,
      'levels': [
        'Números Naturales',
        'Números Enteros',
        'Números Racionales',
        'Suma y Resta',
        'Multiplicación',
        'División',
        'Operaciones Combinadas',
      ],
    },
    {
      'id': 'w2',
      'name': 'Archipiélago Fraccionario',
      'subtitle': 'Mares de Partes y Porcentajes',
      'icon': Icons.pie_chart,
      'color': Colors.orangeAccent,
      'levels': [
        'Equivalencia de Fracciones',
        'Simplificación',
        'Suma/Resta (Distinto Denominador)',
        'Multiplicación/División de Fracciones',
        'Conversión a Decimales',
        'Operaciones con Decimales',
        'Redondeo',
        'Cálculo de Porcentajes',
        'Aumentos y Descuentos',
      ],
    },
    {
      'id': 'w3',
      'name': 'Desierto Proporcional',
      'subtitle': 'El Oasis de las Razones',
      'icon': Icons.balance,
      'color': Colors.amber,
      'levels': [
        'Razones',
        'Proporcionalidad Directa',
        'Proporcionalidad Inversa',
        'Regla de Tres Simple',
        'Regla de Tres Compuesta',
        'Escalas',
      ],
    },
    {
      'id': 'w4',
      'name': 'Caverna de los Primos',
      'subtitle': 'Mina de Factores y Múltiplos',
      'icon': Icons.diamond,
      'color': Colors.purpleAccent,
      'levels': [
        'Factores',
        'Múltiplos',
        'Criterios de Divisibilidad',
        'Números Primos',
        'Descomposición',
        'Máximo Común Divisor (MCD)',
        'Mínimo Común Múltiplo (mcm)',
      ],
    },
    {
      'id': 'w5',
      'name': 'Cumbres de Poder',
      'subtitle': 'Montañas de Exponentes',
      'icon': Icons.bolt,
      'color': Colors.redAccent,
      'levels': [
        'Potencias Básicas',
        'Exponentes',
        'Propiedades de Potencias',
        'Raíz Cuadrada',
        'Raíz Cúbica',
        'Propiedades de Raíces',
      ],
    },
    {
      'id': 'w6',
      'name': 'Ciudad Aplicación',
      'subtitle': 'Matemáticas en el Mundo Real',
      'icon': Icons.location_city,
      'color': Colors.teal,
      'levels': [
        'Problemas Verbales',
        'Modelamiento Aritmético',
        'Estimación',
        'Finanzas Personales',
        'Sistema de Medidas',
        'Matemáticas en Recetas',
      ],
    },
  ];
}
